# Generated by Django 5.1.4 on 2025-01-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=50)),
                ('situacao_atual', models.CharField(max_length=100)),
                ('aliancado_ativo', models.BooleanField(default=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=100)),
                ('naturalidade', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('telefone_emergencia', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_membro', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=255)),
                ('pai', models.CharField(max_length=255)),
                ('nome_conjugue', models.CharField(blank=True, max_length=255, null=True)),
                ('data_casamento', models.DateField(blank=True, null=True)),
                ('igreja_batismo', models.CharField(max_length=100)),
                ('data_batismo', models.DateField()),
                ('tipo_admissao', models.CharField(max_length=100)),
                ('pastor_que_batizou', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('congregacao', models.CharField(max_length=100)),
                ('funcao_igreja', models.CharField(max_length=100)),
                ('ministerio', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_membros/')),
                ('hoje_casamento', models.BooleanField(default=False)),
                ('este_mes_casamento', models.BooleanField(default=False)),
                ('idade_casamento', models.IntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('tem_filhos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='membros.membro')),
            ],
        ),
    ]
